apiVersion: apps/v1
kind: Deployment
metadata:
  name: saas-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      chapter: services
  template:
    metadata:
      labels:
        chapter: services
    spec:
      containers:
        - name: first-api-container
          image: diepulp/saas-api
          ports:
            - containerPort: 8080
